/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArcGisMap: typeof import('./src/components/ArcGisMap.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Header: typeof import('./src/components/Header.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Qrcode: typeof import('./src/components/Qrcode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
