/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthPassword: typeof import('./src/components/auth/password.vue')['default']
    AuthSignup: typeof import('./src/components/auth/signup.vue')['default']
    AuthWechat: typeof import('./src/components/auth/wechat.vue')['default']
    Bimgo: typeof import('./src/components/Bimgo.vue')['default']
    CountDown: typeof import('./src/components/countDown.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    'IconIc:baselineKey': typeof import('~icons/ic/baseline-key')['default']
    'IconIc:baselinePhoneIphone': typeof import('~icons/ic/baseline-phone-iphone')['default']
    'IconIc:baselineWechat': typeof import('~icons/ic/baseline-wechat')['default']
    'IconIc:outlineArrowBack': typeof import('~icons/ic/outline-arrow-back')['default']
    'IconIc:outlineMoreHoriz': typeof import('~icons/ic/outline-more-horiz')['default']
    'IconIc:outlineNotifications': typeof import('~icons/ic/outline-notifications')['default']
    'IconIc:sharpPlus': typeof import('~icons/ic/sharp-plus')['default']
    'IconIconParkOutline:expandRight': typeof import('~icons/icon-park/expand-right')['default']
    'IconIconParkOutline:more': typeof import('~icons/icon-park/more')['default']
    'IconIconParkOutline:remind': typeof import('~icons/icon-park/remind')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    NpButton: typeof import('./src/components/np/button/index.vue')['default']
    NpDropdown: typeof import('./src/components/np/dropdown/index.vue')['default']
    NpDropdownItem: typeof import('./src/components/np/dropdown/item.vue')['default']
    NpDropdownMenu: typeof import('./src/components/np/dropdown/menu.vue')['default']
    NpDropdownSubitem: typeof import('./src/components/np/dropdown/subitem.vue')['default']
    NpInput: typeof import('./src/components/np/input/index.vue')['default']
    NpTooltip: typeof import('./src/components/np/tooltip/index.vue')['default']
    Qrcode: typeof import('./src/components/Qrcode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/index.vue')['default']
  }
}
